### PR TITLE
Add code for rugby example to examples repo #1294

### PR DESCRIPTION
**Pull request by sudip-padhye**
1. I have added the rugby example code and the input CSV file. 
2. The code to save the model has been added however output .nc files are ignored using .gitignore.

### CODE REVIEW

**Comment by OriolAbril** [comment]
It looks like there have been some conflicts, which are due to working on master branch. 

The conflicts can be solved via rebases and so on, however I think the easiest way in this case will be: saving the rugby code in a different folder, deleting the fork and local repository and create them again. Once created, I'd recommend following the advise in the [contributing guide](https://github.com/arviz-devs/arviz/blob/master/CONTRIBUTING.md) to avoid issues like this and working always on a feature branch.

**Comment by sudip-padhye** [comment]
A new pull request has been issued #4  by creating another feature branch "rugby".

**Comment by ahartikainen** [comment]
There is no need to create a new PR. Just update this branch.

**Comment by OriolAbril** [comment]
I would keep #4 and close this one as I commented there.

**Pull request closed without merging**
