### PR TITLE
Add code for school examples to examples repo #1295

### PR DESCRIPTION
**Pull request by sudip-padhye**
Added code for centered_eight and non_centered_eight data to examples by loading the data using arviz.load_arviz_data.  Both files are in python notebooks (.ipynb) with comments added wherever necessary.

### CODE REVIEW

**Comment by canyon289** [comment]
@sudip-padhye Thanks for the contribution. The motivation for this repo is to show the model and code for how the example datasets were generated. This PR only shows how to load the saved inference data.

Would you mind changing this PR to include model and inference run? Ideally in a couple different PPLs?

**Comment by OriolAbril** [comment]
Only the PyMC3 one is enough I think. The most pressing goal is to make the code used to generate the examples in `load_arviz_data` available. In the issue I linked to the PyMC3 model used to generate the corresponding inference data objects, and the data is also available in the same notebooks. This will serve a double goal of helping users understand how the inference data object was generated and will ease updating the datasets whenever we update the inference data scheme. 

It would also be great if you could make sure to use latest ArviZ and xarray releases. You'll see then that `arviz.InferenceData` objects have an html representation like the ones for `xarray.Dataset` and you won't need to have a cell for each group.

**Comment by canyon289** [comment]
@sudip-padhye Why close this? Looks like you were on track

**Comment by sudip-padhye** [comment]
@canyon289 Sorry for that. I initiated a new pull request just now. I did this as I thought the updated files were not uploaded successfully and would need a new Pull Request to be initiated.

**Pull request closed without merging**
